import React, { createContext, useContext, useState, useEffect } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Complete translations for all 8 languages
const resources = {
  ar: {
    translation: {
      // Navigation
      "home": "الرئيسية",
      "ai_hub": "مركز الذكاء الاصطناعي",
      "seniors": "بوابة المتقاعدين",
      "youth": "تمكين الشباب",
      "kids": "عالم الأطفال",
      "cooking": "ركن الطبخ",
      "tourists": "دليل السياح",
      "arab_world": "العالم العربي",
      "subscriptions": "الاشتراكات",
      "profile": "الملف الشخصي",
      "login": "تسجيل الدخول",
      "logout": "تسجيل الخروج",
      "register": "إنشاء حساب",
      
      // Welcome Page
      "welcome_title": "مرحباً بك في دروازة",
      "welcome_subtitle": "بوابتك إلى التراث الكويتي",
      "choose_interface": "اختر واجهتك",
      "heritage_interface": "الواجهة التراثية",
      "heritage_desc": "تجربة أصيلة مع لمسات تقليدية",
      "modern_interface": "الواجهة العصرية",
      "modern_desc": "تصميم حديث وأنيق",
      
      // Common
      "explore": "استكشف",
      "learn_more": "اعرف المزيد",
      "get_started": "ابدأ الآن",
      "view_all": "عرض الكل",
      "search": "بحث",
      "filter": "تصفية",
      "sort": "ترتيب",
      "price": "السعر",
      "category": "الفئة",
      "date": "التاريخ",
      "status": "الحالة",
      "active": "نشط",
      "live": "مباشر",
      "upcoming": "قادم",
      "completed": "مكتمل",
      "coming_soon": "قريباً",
      "join_now": "انضم الآن",
      "watch_video": "شاهد الفيديو",
      "play_now": "العب الآن",
      "try_now": "جرب الآن",
      "subscribe_now": "اشترك الآن",
      "contact_us": "تواصل معنا",
      "notify_me": "أعلمني",
      "save": "حفظ",
      "cancel": "إلغاء",
      "delete": "حذف",
      "edit": "تعديل",
      "close": "إغلاق",
      "back": "رجوع",
      "next": "التالي",
      "previous": "السابق",
      "submit": "إرسال",
      "upload": "رفع",
      "download": "تحميل",
      "share": "مشاركة",
      "copy": "نسخ",
      "success": "نجاح",
      "error": "خطأ",
      "warning": "تحذير",
      "info": "معلومات",
      "loading": "جاري التحميل...",
      
      // AI Hub
      "ai_mentor": "المرشد الذكي",
      "select_model": "اختر النموذج",
      "type_message": "اكتب رسالتك...",
      "send": "إرسال",
      "chat_history": "سجل المحادثات",
      
      // Seniors
      "marketplace": "سوق التحف",
      "tale_councils": "مجالس الحكايات",
      "expertise_academy": "أكاديمية الخبرات",
      "sell_item": "بيع منتج",
      "host_council": "استضافة مجلس",
      "join_council": "انضم للمجلس",
      "live_now": "مباشر الآن",
      "remind_me": "ذكرني",
      
      // Youth
      "career_path": "المسار المهني",
      "design_lab": "مختبر التصميم",
      "workshops": "ورش العمل",
      "join_community": "انضم للمجتمع",
      
      // Kids
      "games": "الألعاب",
      "heritage_box": "صندوق التراث",
      "achievements": "الإنجازات",
      "meet_mentor": "قابل المرشد",
      
      // Cooking
      "recipes": "الوصفات",
      "ar_kitchen": "المطبخ بالواقع المعزز",
      
      // Subscriptions
      "choose_plan": "اختر خطتك",
      "monthly": "شهري",
      "yearly": "سنوي",
      "subscribe": "اشترك",
      "features": "المميزات",
      "free": "مجاني",
      "family": "العائلة",
      "heritage_plus": "التراث المميز",
      "premium": "بريميوم",
      "current_plan": "الخطة الحالية",
      "payment_method": "طريقة الدفع",
      
      // Auth
      "email": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "confirm_password": "تأكيد كلمة المرور",
      "name": "الاسم",
      "continue_with_google": "المتابعة مع جوجل",
      "or": "أو",
      "already_have_account": "لديك حساب؟",
      "dont_have_account": "ليس لديك حساب؟",
      
      // Footer
      "about_us": "من نحن",
      "contact": "اتصل بنا",
      "privacy": "الخصوصية",
      "terms": "الشروط",
      "copyright": "© 2025 دروازة. جميع الحقوق محفوظة."
    }
  },
  en: {
    translation: {
      "home": "Home",
      "ai_hub": "AI Hub",
      "seniors": "Seniors Gateway",
      "youth": "Youth Empowerment",
      "kids": "Kids World",
      "cooking": "Cooking Corner",
      "tourists": "Tourist Guide",
      "arab_world": "Arab World",
      "subscriptions": "Subscriptions",
      "profile": "Profile",
      "login": "Login",
      "logout": "Logout",
      "register": "Register",
      "welcome_title": "Welcome to Darwaza",
      "welcome_subtitle": "Your Gateway to Kuwaiti Heritage",
      "choose_interface": "Choose Your Interface",
      "heritage_interface": "Heritage Interface",
      "heritage_desc": "An authentic experience with traditional touches",
      "modern_interface": "Modern Interface",
      "modern_desc": "Sleek and contemporary design",
      "explore": "Explore",
      "learn_more": "Learn More",
      "get_started": "Get Started",
      "view_all": "View All",
      "search": "Search",
      "filter": "Filter",
      "sort": "Sort",
      "price": "Price",
      "category": "Category",
      "date": "Date",
      "status": "Status",
      "active": "Active",
      "live": "Live",
      "upcoming": "Upcoming",
      "completed": "Completed",
      "coming_soon": "Coming Soon",
      "join_now": "Join Now",
      "watch_video": "Watch Video",
      "play_now": "Play Now",
      "try_now": "Try Now",
      "subscribe_now": "Subscribe Now",
      "contact_us": "Contact Us",
      "notify_me": "Notify Me",
      "save": "Save",
      "cancel": "Cancel",
      "delete": "Delete",
      "edit": "Edit",
      "close": "Close",
      "back": "Back",
      "next": "Next",
      "previous": "Previous",
      "submit": "Submit",
      "upload": "Upload",
      "download": "Download",
      "share": "Share",
      "copy": "Copy",
      "success": "Success",
      "error": "Error",
      "warning": "Warning",
      "info": "Info",
      "loading": "Loading...",
      "ai_mentor": "AI Mentor",
      "select_model": "Select Model",
      "type_message": "Type your message...",
      "send": "Send",
      "chat_history": "Chat History",
      "marketplace": "Antique Market",
      "tale_councils": "Tale Councils",
      "expertise_academy": "Expertise Academy",
      "sell_item": "Sell Item",
      "host_council": "Host Council",
      "join_council": "Join Council",
      "live_now": "Live Now",
      "remind_me": "Remind Me",
      "career_path": "Career Path",
      "design_lab": "Design Lab",
      "workshops": "Workshops",
      "join_community": "Join Community",
      "games": "Games",
      "heritage_box": "Heritage Box",
      "achievements": "Achievements",
      "meet_mentor": "Meet Mentor",
      "recipes": "Recipes",
      "ar_kitchen": "AR Kitchen",
      "choose_plan": "Choose Your Plan",
      "monthly": "Monthly",
      "yearly": "Yearly",
      "subscribe": "Subscribe",
      "features": "Features",
      "free": "Free",
      "family": "Family",
      "heritage_plus": "Heritage Plus",
      "premium": "Premium",
      "current_plan": "Current Plan",
      "payment_method": "Payment Method",
      "email": "Email",
      "password": "Password",
      "confirm_password": "Confirm Password",
      "name": "Name",
      "continue_with_google": "Continue with Google",
      "or": "or",
      "already_have_account": "Already have an account?",
      "dont_have_account": "Don't have an account?",
      "about_us": "About Us",
      "contact": "Contact",
      "privacy": "Privacy",
      "terms": "Terms",
      "copyright": "© 2025 Darwaza. All rights reserved."
    }
  },
  es: {
    translation: {
      "home": "Inicio",
      "ai_hub": "Centro de IA",
      "seniors": "Portal de Mayores",
      "youth": "Empoderamiento Juvenil",
      "kids": "Mundo Infantil",
      "cooking": "Rincón de Cocina",
      "tourists": "Guía Turística",
      "arab_world": "Mundo Árabe",
      "subscriptions": "Suscripciones",
      "profile": "Perfil",
      "login": "Iniciar Sesión",
      "logout": "Cerrar Sesión",
      "register": "Registrarse",
      "welcome_title": "Bienvenido a Darwaza",
      "welcome_subtitle": "Tu Puerta al Patrimonio Kuwaití",
      "choose_interface": "Elige Tu Interfaz",
      "heritage_interface": "Interfaz Patrimonial",
      "heritage_desc": "Una experiencia auténtica con toques tradicionales",
      "modern_interface": "Interfaz Moderna",
      "modern_desc": "Diseño elegante y contemporáneo",
      "explore": "Explorar",
      "learn_more": "Saber Más",
      "get_started": "Comenzar",
      "view_all": "Ver Todo",
      "search": "Buscar",
      "filter": "Filtrar",
      "sort": "Ordenar",
      "price": "Precio",
      "category": "Categoría",
      "date": "Fecha",
      "status": "Estado",
      "active": "Activo",
      "live": "En Vivo",
      "upcoming": "Próximo",
      "completed": "Completado",
      "coming_soon": "Próximamente",
      "join_now": "Únete Ahora",
      "watch_video": "Ver Video",
      "play_now": "Jugar Ahora",
      "try_now": "Probar Ahora",
      "subscribe_now": "Suscribirse Ahora",
      "contact_us": "Contáctanos",
      "notify_me": "Notificarme",
      "save": "Guardar",
      "cancel": "Cancelar",
      "delete": "Eliminar",
      "edit": "Editar",
      "close": "Cerrar",
      "back": "Atrás",
      "next": "Siguiente",
      "previous": "Anterior",
      "submit": "Enviar",
      "upload": "Subir",
      "download": "Descargar",
      "share": "Compartir",
      "copy": "Copiar",
      "success": "Éxito",
      "error": "Error",
      "warning": "Advertencia",
      "info": "Información",
      "loading": "Cargando...",
      "ai_mentor": "Mentor IA",
      "select_model": "Seleccionar Modelo",
      "type_message": "Escribe tu mensaje...",
      "send": "Enviar",
      "chat_history": "Historial de Chat",
      "marketplace": "Mercado de Antigüedades",
      "tale_councils": "Consejos de Cuentos",
      "expertise_academy": "Academia de Expertos",
      "sell_item": "Vender Artículo",
      "host_council": "Organizar Consejo",
      "join_council": "Unirse al Consejo",
      "live_now": "En Vivo Ahora",
      "remind_me": "Recordarme",
      "career_path": "Carrera Profesional",
      "design_lab": "Laboratorio de Diseño",
      "workshops": "Talleres",
      "join_community": "Unirse a la Comunidad",
      "games": "Juegos",
      "heritage_box": "Caja del Patrimonio",
      "achievements": "Logros",
      "meet_mentor": "Conocer al Mentor",
      "recipes": "Recetas",
      "ar_kitchen": "Cocina AR",
      "choose_plan": "Elige Tu Plan",
      "monthly": "Mensual",
      "yearly": "Anual",
      "subscribe": "Suscribirse",
      "features": "Características",
      "free": "Gratis",
      "family": "Familia",
      "heritage_plus": "Patrimonio Plus",
      "premium": "Premium",
      "current_plan": "Plan Actual",
      "payment_method": "Método de Pago",
      "email": "Correo Electrónico",
      "password": "Contraseña",
      "confirm_password": "Confirmar Contraseña",
      "name": "Nombre",
      "continue_with_google": "Continuar con Google",
      "or": "o",
      "already_have_account": "¿Ya tienes una cuenta?",
      "dont_have_account": "¿No tienes una cuenta?",
      "about_us": "Sobre Nosotros",
      "contact": "Contacto",
      "privacy": "Privacidad",
      "terms": "Términos",
      "copyright": "© 2025 Darwaza. Todos los derechos reservados."
    }
  },
  fr: {
    translation: {
      "home": "Accueil",
      "ai_hub": "Centre IA",
      "seniors": "Portail des Aînés",
      "youth": "Autonomisation des Jeunes",
      "kids": "Monde des Enfants",
      "cooking": "Coin Cuisine",
      "tourists": "Guide Touristique",
      "arab_world": "Monde Arabe",
      "subscriptions": "Abonnements",
      "profile": "Profil",
      "login": "Connexion",
      "logout": "Déconnexion",
      "register": "S'inscrire",
      "welcome_title": "Bienvenue à Darwaza",
      "welcome_subtitle": "Votre Porte vers le Patrimoine Koweïtien",
      "choose_interface": "Choisissez Votre Interface",
      "heritage_interface": "Interface Patrimoniale",
      "heritage_desc": "Une expérience authentique avec des touches traditionnelles",
      "modern_interface": "Interface Moderne",
      "modern_desc": "Design élégant et contemporain",
      "explore": "Explorer",
      "learn_more": "En Savoir Plus",
      "get_started": "Commencer",
      "view_all": "Voir Tout",
      "search": "Rechercher",
      "filter": "Filtrer",
      "sort": "Trier",
      "price": "Prix",
      "category": "Catégorie",
      "date": "Date",
      "status": "Statut",
      "active": "Actif",
      "live": "En Direct",
      "upcoming": "À Venir",
      "completed": "Terminé",
      "coming_soon": "Bientôt Disponible",
      "join_now": "Rejoindre Maintenant",
      "watch_video": "Regarder la Vidéo",
      "play_now": "Jouer Maintenant",
      "try_now": "Essayer Maintenant",
      "subscribe_now": "S'abonner Maintenant",
      "contact_us": "Nous Contacter",
      "notify_me": "Me Notifier",
      "save": "Enregistrer",
      "cancel": "Annuler",
      "delete": "Supprimer",
      "edit": "Modifier",
      "close": "Fermer",
      "back": "Retour",
      "next": "Suivant",
      "previous": "Précédent",
      "submit": "Soumettre",
      "upload": "Télécharger",
      "download": "Télécharger",
      "share": "Partager",
      "copy": "Copier",
      "success": "Succès",
      "error": "Erreur",
      "warning": "Avertissement",
      "info": "Information",
      "loading": "Chargement...",
      "ai_mentor": "Mentor IA",
      "select_model": "Sélectionner le Modèle",
      "type_message": "Tapez votre message...",
      "send": "Envoyer",
      "chat_history": "Historique des Discussions",
      "marketplace": "Marché des Antiquités",
      "tale_councils": "Conseils des Contes",
      "expertise_academy": "Académie d'Expertise",
      "sell_item": "Vendre un Article",
      "host_council": "Organiser un Conseil",
      "join_council": "Rejoindre le Conseil",
      "live_now": "En Direct Maintenant",
      "remind_me": "Me Rappeler",
      "career_path": "Parcours Professionnel",
      "design_lab": "Laboratoire de Design",
      "workshops": "Ateliers",
      "join_community": "Rejoindre la Communauté",
      "games": "Jeux",
      "heritage_box": "Boîte du Patrimoine",
      "achievements": "Réalisations",
      "meet_mentor": "Rencontrer le Mentor",
      "recipes": "Recettes",
      "ar_kitchen": "Cuisine RA",
      "choose_plan": "Choisissez Votre Plan",
      "monthly": "Mensuel",
      "yearly": "Annuel",
      "subscribe": "S'abonner",
      "features": "Fonctionnalités",
      "free": "Gratuit",
      "family": "Famille",
      "heritage_plus": "Patrimoine Plus",
      "premium": "Premium",
      "current_plan": "Plan Actuel",
      "payment_method": "Méthode de Paiement",
      "email": "E-mail",
      "password": "Mot de Passe",
      "confirm_password": "Confirmer le Mot de Passe",
      "name": "Nom",
      "continue_with_google": "Continuer avec Google",
      "or": "ou",
      "already_have_account": "Vous avez déjà un compte?",
      "dont_have_account": "Vous n'avez pas de compte?",
      "about_us": "À Propos",
      "contact": "Contact",
      "privacy": "Confidentialité",
      "terms": "Conditions",
      "copyright": "© 2025 Darwaza. Tous droits réservés."
    }
  },
  ja: {
    translation: {
      "home": "ホーム",
      "ai_hub": "AIハブ",
      "seniors": "シニアゲートウェイ",
      "youth": "若者エンパワーメント",
      "kids": "キッズワールド",
      "cooking": "クッキングコーナー",
      "tourists": "観光ガイド",
      "arab_world": "アラブ世界",
      "subscriptions": "サブスクリプション",
      "profile": "プロフィール",
      "login": "ログイン",
      "logout": "ログアウト",
      "register": "登録",
      "welcome_title": "Darwazaへようこそ",
      "welcome_subtitle": "クウェートの遺産への入り口",
      "choose_interface": "インターフェースを選択",
      "heritage_interface": "伝統インターフェース",
      "heritage_desc": "伝統的なタッチの本格的な体験",
      "modern_interface": "モダンインターフェース",
      "modern_desc": "洗練された現代的なデザイン",
      "explore": "探索",
      "learn_more": "詳細を見る",
      "get_started": "始める",
      "view_all": "すべて見る",
      "search": "検索",
      "filter": "フィルター",
      "sort": "並べ替え",
      "price": "価格",
      "category": "カテゴリー",
      "date": "日付",
      "status": "ステータス",
      "active": "アクティブ",
      "live": "ライブ",
      "upcoming": "近日公開",
      "completed": "完了",
      "coming_soon": "近日公開",
      "join_now": "今すぐ参加",
      "watch_video": "動画を見る",
      "play_now": "今すぐプレイ",
      "try_now": "今すぐ試す",
      "subscribe_now": "今すぐ登録",
      "contact_us": "お問い合わせ",
      "notify_me": "通知する",
      "save": "保存",
      "cancel": "キャンセル",
      "delete": "削除",
      "edit": "編集",
      "close": "閉じる",
      "back": "戻る",
      "next": "次へ",
      "previous": "前へ",
      "submit": "送信",
      "upload": "アップロード",
      "download": "ダウンロード",
      "share": "共有",
      "copy": "コピー",
      "success": "成功",
      "error": "エラー",
      "warning": "警告",
      "info": "情報",
      "loading": "読み込み中...",
      "ai_mentor": "AIメンター",
      "select_model": "モデルを選択",
      "type_message": "メッセージを入力...",
      "send": "送信",
      "chat_history": "チャット履歴",
      "marketplace": "アンティーク市場",
      "tale_councils": "物語評議会",
      "expertise_academy": "専門アカデミー",
      "sell_item": "商品を売る",
      "host_council": "評議会を主催",
      "join_council": "評議会に参加",
      "live_now": "ライブ中",
      "remind_me": "リマインドする",
      "career_path": "キャリアパス",
      "design_lab": "デザインラボ",
      "workshops": "ワークショップ",
      "join_community": "コミュニティに参加",
      "games": "ゲーム",
      "heritage_box": "ヘリテージボックス",
      "achievements": "実績",
      "meet_mentor": "メンターに会う",
      "recipes": "レシピ",
      "ar_kitchen": "ARキッチン",
      "choose_plan": "プランを選択",
      "monthly": "月額",
      "yearly": "年額",
      "subscribe": "登録",
      "features": "機能",
      "free": "無料",
      "family": "ファミリー",
      "heritage_plus": "ヘリテージプラス",
      "premium": "プレミアム",
      "current_plan": "現在のプラン",
      "payment_method": "支払い方法",
      "email": "メール",
      "password": "パスワード",
      "confirm_password": "パスワード確認",
      "name": "名前",
      "continue_with_google": "Googleで続行",
      "or": "または",
      "already_have_account": "すでにアカウントをお持ちですか？",
      "dont_have_account": "アカウントをお持ちでないですか？",
      "about_us": "会社概要",
      "contact": "お問い合わせ",
      "privacy": "プライバシー",
      "terms": "利用規約",
      "copyright": "© 2025 Darwaza. All rights reserved."
    }
  },
  zh: {
    translation: {
      "home": "首页",
      "ai_hub": "AI中心",
      "seniors": "老年人门户",
      "youth": "青年赋能",
      "kids": "儿童世界",
      "cooking": "烹饪角",
      "tourists": "旅游指南",
      "arab_world": "阿拉伯世界",
      "subscriptions": "订阅",
      "profile": "个人资料",
      "login": "登录",
      "logout": "退出",
      "register": "注册",
      "welcome_title": "欢迎来到Darwaza",
      "welcome_subtitle": "通往科威特遗产的大门",
      "choose_interface": "选择您的界面",
      "heritage_interface": "传统界面",
      "heritage_desc": "带有传统元素的真实体验",
      "modern_interface": "现代界面",
      "modern_desc": "时尚现代的设计",
      "explore": "探索",
      "learn_more": "了解更多",
      "get_started": "开始使用",
      "view_all": "查看全部",
      "search": "搜索",
      "filter": "筛选",
      "sort": "排序",
      "price": "价格",
      "category": "类别",
      "date": "日期",
      "status": "状态",
      "active": "活跃",
      "live": "直播",
      "upcoming": "即将推出",
      "completed": "已完成",
      "coming_soon": "即将推出",
      "join_now": "立即加入",
      "watch_video": "观看视频",
      "play_now": "立即玩",
      "try_now": "立即尝试",
      "subscribe_now": "立即订阅",
      "contact_us": "联系我们",
      "notify_me": "通知我",
      "save": "保存",
      "cancel": "取消",
      "delete": "删除",
      "edit": "编辑",
      "close": "关闭",
      "back": "返回",
      "next": "下一步",
      "previous": "上一步",
      "submit": "提交",
      "upload": "上传",
      "download": "下载",
      "share": "分享",
      "copy": "复制",
      "success": "成功",
      "error": "错误",
      "warning": "警告",
      "info": "信息",
      "loading": "加载中...",
      "ai_mentor": "AI导师",
      "select_model": "选择模型",
      "type_message": "输入您的消息...",
      "send": "发送",
      "chat_history": "聊天记录",
      "marketplace": "古董市场",
      "tale_councils": "故事会",
      "expertise_academy": "专家学院",
      "sell_item": "出售物品",
      "host_council": "主持会议",
      "join_council": "加入会议",
      "live_now": "正在直播",
      "remind_me": "提醒我",
      "career_path": "职业路径",
      "design_lab": "设计实验室",
      "workshops": "工作坊",
      "join_community": "加入社区",
      "games": "游戏",
      "heritage_box": "遗产盒",
      "achievements": "成就",
      "meet_mentor": "见导师",
      "recipes": "食谱",
      "ar_kitchen": "AR厨房",
      "choose_plan": "选择您的计划",
      "monthly": "月付",
      "yearly": "年付",
      "subscribe": "订阅",
      "features": "功能",
      "free": "免费",
      "family": "家庭",
      "heritage_plus": "遗产增强版",
      "premium": "高级版",
      "current_plan": "当前计划",
      "payment_method": "支付方式",
      "email": "电子邮件",
      "password": "密码",
      "confirm_password": "确认密码",
      "name": "姓名",
      "continue_with_google": "使用Google继续",
      "or": "或",
      "already_have_account": "已有账户？",
      "dont_have_account": "没有账户？",
      "about_us": "关于我们",
      "contact": "联系方式",
      "privacy": "隐私",
      "terms": "条款",
      "copyright": "© 2025 Darwaza. 保留所有权利。"
    }
  },
  ru: {
    translation: {
      "home": "Главная",
      "ai_hub": "AI Центр",
      "seniors": "Портал для Пожилых",
      "youth": "Молодёжное Развитие",
      "kids": "Детский Мир",
      "cooking": "Кулинарный Уголок",
      "tourists": "Туристический Гид",
      "arab_world": "Арабский Мир",
      "subscriptions": "Подписки",
      "profile": "Профиль",
      "login": "Войти",
      "logout": "Выйти",
      "register": "Регистрация",
      "welcome_title": "Добро пожаловать в Darwaza",
      "welcome_subtitle": "Ваши врата к кувейтскому наследию",
      "choose_interface": "Выберите Интерфейс",
      "heritage_interface": "Традиционный Интерфейс",
      "heritage_desc": "Аутентичный опыт с традиционными элементами",
      "modern_interface": "Современный Интерфейс",
      "modern_desc": "Элегантный современный дизайн",
      "explore": "Исследовать",
      "learn_more": "Узнать Больше",
      "get_started": "Начать",
      "view_all": "Показать Всё",
      "search": "Поиск",
      "filter": "Фильтр",
      "sort": "Сортировка",
      "price": "Цена",
      "category": "Категория",
      "date": "Дата",
      "status": "Статус",
      "active": "Активный",
      "live": "Прямой Эфир",
      "upcoming": "Скоро",
      "completed": "Завершено",
      "coming_soon": "Скоро",
      "join_now": "Присоединиться",
      "watch_video": "Смотреть Видео",
      "play_now": "Играть Сейчас",
      "try_now": "Попробовать Сейчас",
      "subscribe_now": "Подписаться Сейчас",
      "contact_us": "Связаться с Нами",
      "notify_me": "Уведомить Меня",
      "save": "Сохранить",
      "cancel": "Отмена",
      "delete": "Удалить",
      "edit": "Редактировать",
      "close": "Закрыть",
      "back": "Назад",
      "next": "Далее",
      "previous": "Назад",
      "submit": "Отправить",
      "upload": "Загрузить",
      "download": "Скачать",
      "share": "Поделиться",
      "copy": "Копировать",
      "success": "Успех",
      "error": "Ошибка",
      "warning": "Предупреждение",
      "info": "Информация",
      "loading": "Загрузка...",
      "ai_mentor": "AI Наставник",
      "select_model": "Выбрать Модель",
      "type_message": "Введите сообщение...",
      "send": "Отправить",
      "chat_history": "История Чата",
      "marketplace": "Антикварный Рынок",
      "tale_councils": "Советы Сказок",
      "expertise_academy": "Академия Экспертов",
      "sell_item": "Продать Товар",
      "host_council": "Организовать Совет",
      "join_council": "Присоединиться к Совету",
      "live_now": "Сейчас в Эфире",
      "remind_me": "Напомнить",
      "career_path": "Карьерный Путь",
      "design_lab": "Дизайн Лаборатория",
      "workshops": "Мастерские",
      "join_community": "Присоединиться к Сообществу",
      "games": "Игры",
      "heritage_box": "Коробка Наследия",
      "achievements": "Достижения",
      "meet_mentor": "Встретить Наставника",
      "recipes": "Рецепты",
      "ar_kitchen": "AR Кухня",
      "choose_plan": "Выберите План",
      "monthly": "Месячный",
      "yearly": "Годовой",
      "subscribe": "Подписаться",
      "features": "Функции",
      "free": "Бесплатно",
      "family": "Семья",
      "heritage_plus": "Наследие Плюс",
      "premium": "Премиум",
      "current_plan": "Текущий План",
      "payment_method": "Способ Оплаты",
      "email": "Email",
      "password": "Пароль",
      "confirm_password": "Подтвердить Пароль",
      "name": "Имя",
      "continue_with_google": "Продолжить с Google",
      "or": "или",
      "already_have_account": "Уже есть аккаунт?",
      "dont_have_account": "Нет аккаунта?",
      "about_us": "О Нас",
      "contact": "Контакты",
      "privacy": "Конфиденциальность",
      "terms": "Условия",
      "copyright": "© 2025 Darwaza. Все права защищены."
    }
  },
  hi: {
    translation: {
      "home": "होम",
      "ai_hub": "AI हब",
      "seniors": "वरिष्ठ गेटवे",
      "youth": "युवा सशक्तिकरण",
      "kids": "बच्चों की दुनिया",
      "cooking": "खाना पकाने का कोना",
      "tourists": "पर्यटक गाइड",
      "arab_world": "अरब विश्व",
      "subscriptions": "सदस्यता",
      "profile": "प्रोफ़ाइल",
      "login": "लॉग इन",
      "logout": "लॉग आउट",
      "register": "रजिस्टर",
      "welcome_title": "Darwaza में आपका स्वागत है",
      "welcome_subtitle": "कुवैती विरासत का द्वार",
      "choose_interface": "अपना इंटरफ़ेस चुनें",
      "heritage_interface": "विरासत इंटरफ़ेस",
      "heritage_desc": "पारंपरिक स्पर्श के साथ प्रामाणिक अनुभव",
      "modern_interface": "आधुनिक इंटरफ़ेस",
      "modern_desc": "सुरुचिपूर्ण और समकालीन डिज़ाइन",
      "explore": "खोजें",
      "learn_more": "और जानें",
      "get_started": "शुरू करें",
      "view_all": "सभी देखें",
      "search": "खोज",
      "filter": "फ़िल्टर",
      "sort": "क्रमबद्ध करें",
      "price": "कीमत",
      "category": "श्रेणी",
      "date": "तारीख",
      "status": "स्थिति",
      "active": "सक्रिय",
      "live": "लाइव",
      "upcoming": "आगामी",
      "completed": "पूर्ण",
      "coming_soon": "जल्द आ रहा है",
      "join_now": "अभी शामिल हों",
      "watch_video": "वीडियो देखें",
      "play_now": "अभी खेलें",
      "try_now": "अभी आज़माएं",
      "subscribe_now": "अभी सदस्यता लें",
      "contact_us": "हमसे संपर्क करें",
      "notify_me": "मुझे सूचित करें",
      "save": "सहेजें",
      "cancel": "रद्द करें",
      "delete": "हटाएं",
      "edit": "संपादित करें",
      "close": "बंद करें",
      "back": "वापस",
      "next": "अगला",
      "previous": "पिछला",
      "submit": "जमा करें",
      "upload": "अपलोड करें",
      "download": "डाउनलोड करें",
      "share": "साझा करें",
      "copy": "कॉपी करें",
      "success": "सफलता",
      "error": "त्रुटि",
      "warning": "चेतावनी",
      "info": "जानकारी",
      "loading": "लोड हो रहा है...",
      "ai_mentor": "AI मेंटर",
      "select_model": "मॉडल चुनें",
      "type_message": "अपना संदेश लिखें...",
      "send": "भेजें",
      "chat_history": "चैट इतिहास",
      "marketplace": "प्राचीन वस्तुओं का बाज़ार",
      "tale_councils": "कहानी परिषद",
      "expertise_academy": "विशेषज्ञता अकादमी",
      "sell_item": "वस्तु बेचें",
      "host_council": "परिषद की मेज़बानी करें",
      "join_council": "परिषद में शामिल हों",
      "live_now": "अभी लाइव",
      "remind_me": "मुझे याद दिलाएं",
      "career_path": "करियर पथ",
      "design_lab": "डिज़ाइन लैब",
      "workshops": "कार्यशालाएं",
      "join_community": "समुदाय में शामिल हों",
      "games": "खेल",
      "heritage_box": "विरासत बॉक्स",
      "achievements": "उपलब्धियां",
      "meet_mentor": "मेंटर से मिलें",
      "recipes": "व्यंजन विधि",
      "ar_kitchen": "AR किचन",
      "choose_plan": "अपनी योजना चुनें",
      "monthly": "मासिक",
      "yearly": "वार्षिक",
      "subscribe": "सदस्यता लें",
      "features": "विशेषताएं",
      "free": "मुफ़्त",
      "family": "परिवार",
      "heritage_plus": "विरासत प्लस",
      "premium": "प्रीमियम",
      "current_plan": "वर्तमान योजना",
      "payment_method": "भुगतान का तरीका",
      "email": "ईमेल",
      "password": "पासवर्ड",
      "confirm_password": "पासवर्ड की पुष्टि करें",
      "name": "नाम",
      "continue_with_google": "Google से जारी रखें",
      "or": "या",
      "already_have_account": "पहले से खाता है?",
      "dont_have_account": "खाता नहीं है?",
      "about_us": "हमारे बारे में",
      "contact": "संपर्क",
      "privacy": "गोपनीयता",
      "terms": "नियम",
      "copyright": "© 2025 Darwaza. सर्वाधिकार सुरक्षित।"
    }
  }
};

// Initialize i18n
i18n.use(initReactI18next).init({
  resources,
  lng: 'ar',
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false
  }
});

const RTL_LANGUAGES = ['ar'];

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'ar', name: 'العربية', nativeName: 'العربية', flag: '🇰🇼' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' }
];

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('darwaza-language') || 'ar';
  });

  const isRTL = RTL_LANGUAGES.includes(language);

  useEffect(() => {
    localStorage.setItem('darwaza-language', language);
    i18n.changeLanguage(language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang) => {
    setLanguageState(lang);
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      isRTL,
      languages: LANGUAGES,
      t: i18n.t.bind(i18n)
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default i18n;
